### ISSUE TITLE
WHAT IS THIS REPO BRO

### ISSUE THREAD

**Issue by Kuugang** [Requiem53/DFA-With-Game-Theory#1]
![image](https://github.com/user-attachments/assets/e7214cc5-937a-4ca7-851a-e5549b0861d6)

**Comment by avrilnigelchua0412** [comment]
![anna-yanami-yanami-anna](https://github.com/user-attachments/assets/affeef92-6e99-4efd-ac22-0c91d7785fbc)

**Comment by Requiem53** [comment]
Hayaan mo na munang maidlip
At huwag mong isiping balewala ka sa akin
At kung magdilim, huwag mong pansinin
Ang panaginip kong bitin na makapiling lang kita
Kahit wala sa piling, 'di mo lang napapansin
Dahil itong damdaming ikaw ang lagi nang hiling
Gustong-gusto ko nang makita ka't muling nasasabik sa 'yo't
Hindi na makapaghintay sa 'yong pagbabalik
At huwag mong isipin na balewala, sinta
Gustong-gusto nang makapiling lang kita
Hayaan mo na munang maidlip
At huwag mong isiping balewala ka sa akin
At kung magdilim, huwag mong pansinin
Ang panaginip kong bitin na makapiling lang kita
Kahit wala sa piling, 'di mo lang napapansin
Dahil itong damdaming ikaw ang lagi nang hiling
Gustong-gusto ko nang makita ka't muling nasasabik sa 'yo't
Hindi na makapaghintay sa 'yong pagbabalik
At huwag mong isipin na balewala, sinta
Gustong-gusto nang makapiling lang kita
Kahit na ano'ng gawin, sabihin
Pipilitin ko pa ring mapalapit lamang sa 'yo
At kahit pa matapos na ang sandaling pinagmulan nito
Lahat-lahat sa isip ko, whoa
Gustong-gusto ko nang makita ka't muling nasasabik sa 'yo't
Hindi na makapaghintay sa 'yong pagbabalik
Gustong-gusto ko nang makita ka't muling nasasabik sa 'yo't
Hindi na makapaghintay sa 'yong pagbabalik
Sa 'yong pagbabalik
(Gustong-gusto ko na)

**Comment by Requiem53** [comment]
im gonna close this okay
